package no.uio.ifi.in2000.rakettoppskytning.ui.theme

import androidx.compose.ui.graphics.Color

val primaryDark = Color(0xFFB0C6FF)
val onPrimaryDark = Color(0xFF142F60)
val primaryContainerDark = Color(0xFF2E4578)
val onPrimaryContainerDark = Color(0xFFD9E2FF)
val secondaryDark = Color(0xFF98CCF9)
val onSecondaryDark = Color(0xFF003350)
val secondaryContainerDark = Color(0xFF034B71)
val onSecondaryContainerDark = Color(0xFFCBE6FF)
val tertiaryDark = Color(0xFFB6C4FF)
val onTertiaryDark = Color(0xFF1D2D61)
val tertiaryContainerDark = Color(0xFF354479)
val onTertiaryContainerDark = Color(0xFFDCE1FF)
val errorDark = Color(0xFFFFB3B0)
val onErrorDark = Color(0xFF571D1E)
val errorContainerDark = Color(0xFF733332)
val onErrorContainerDark = Color(0xFFFFDAD8)
val backgroundDark = Color(0xFF121318)
val onBackgroundDark = Color(0xFFE2E2E9)
val surfaceDark = Color(0xFF121318)
val onSurfaceDark = Color(0xFFE2E2E9)
val surfaceVariantDark = Color(0xFF44464F)
val onSurfaceVariantDark = Color(0xFFC5C6D0)
val outlineDark = Color(0xFF8F9099)
val outlineVariantDark = Color(0xFF44464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E9)
val inverseOnSurfaceDark = Color(0xFF2F3036)
val inversePrimaryDark = Color(0xFF465D91)
val surfaceDimDark = Color(0xFF121318)
val surfaceBrightDark = Color(0xFF38393F)
val surfaceContainerLowestDark = Color(0xFF0C0E13)
val surfaceContainerLowDark = Color(0xFF1A1B20)
val surfaceContainerDark = Color(0xFF1E1F25)
val surfaceContainerHighDark = Color(0xFF282A2F)
val surfaceContainerHighestDark = Color(0xFF33353A)

//------------- LIGHT SCHEME ---------------------------------------------
val primaryLight = Color(0xFF465D91)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD9E2FF)
val onPrimaryContainerLight = Color(0xFF001944)

val secondaryLight = Color(0xFF2A638A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCBE6FF)
val onSecondaryContainerLight = Color(0xFF001E31)

val tertiaryLight = Color(0xFF4D5C92)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDCE1FF)
val onTertiaryContainerLight = Color(0xFF04174B)

val errorLight = Color(0xFF904A48)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD8)
val onErrorContainerLight = Color(0xFF3B080B)

val backgroundLight = Color(0xFFFAF8FF)
val onBackgroundLight = Color(0xFF1A1B20)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF1A1B20)
val surfaceVariantLight = Color(0xFFE1E2EC)
val onSurfaceVariantLight = Color(0xFF44464F)
val outlineLight = Color(0xFF757780)
val outlineVariantLight = Color(0xFFC5C6D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF1F0F7)
val inversePrimaryLight = Color(0xFFB0C6FF)
val surfaceDimLight = Color(0xFFDAD9E0)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F3FA)
val surfaceContainerLight = Color(0xFFEEEDF4)
val surfaceContainerHighLight = Color(0xFFE8E7EF)
val surfaceContainerHighestLight = Color(0xFFE2E2E9)